export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SET_SECTION = 'SET_SECTION';
export const SET_DRAFTS = 'SET_DRAFTS';
export const SET_SELECTED_DRAFT = 'SET_SELECTED_DRAFT';
export const SET_LISTS = 'SET_LISTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const CREATE_NEW_DRAFT = 'CREATE_NEW_DRAFT';
export const REMOVE_NEW_DRAFT = 'REMOVE_NEW_DRAFT';

