export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const SET_SECTION = 'SET_SECTION';

export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SET_LISTS = 'SET_LISTS';

export const SET_DRAFT_PRODUCTS = 'SET_PRODUCTS';

export const SET_PRODUCT = 'SET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const SET_SUGGESTED_PRODUCTS = 'SET_SUGGESTED_PRODUCTS';


